---
title: 'Module #1 Essay'
author: "YiWei Yang (18422148)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---
###Microbial life can easily live without us; we, however, cannot survive without the global catalysis and environmental transformations it provides

  Microbes are considered as the basic unit of life and have long existed in a mutualistic relationship with eukaryotes. Microbes provide humans with essential nutrients, drives important metabolic processes that give rise to formation of earth’s atmosphere, oceans and sediments. Because of those reasons, I would agree with the statement such that microbes are essential for the survival of human beings and have given risen to the planet earth that exists nowadays. Meanwhile, microbes are found to exist in ancient earth long before the earth has transformed to be survivable for human beings. Ancient earth is anaerobic and contains toxic chemicals such as methane that aren’t tolerant for humans; microbes has also been found to exist in harsh environments in nowadays earth such as in high heat or pH conditions. Therefore, microbes aren’t depend on human beings for survival. Overall, microbial life can easily live without us, but human beings cannot survive without the global catalysis and environmental transformation provided by microbes.

  Frist of all, mitochondria as the crucial component of cellular respiration and has generated the major energy source ATP for usage of living organisms, is found to originate from α-proteobacterial ancestor (1). Such bacteria has been engulfed by an eukaryotic cells and existed within them in a symbiotic relationship over thousands of years. Mitochondria allows for human beings to efficiently utilize carbon and oxygen sources, and synthesize ATP as the energy source for majority of cellular processes. Mitochondria has been a crucial survival component for human beings, and without this organ human beings should acquire energy using different means. Since mitochondria is originated from a bacterial species, the survival of all types of living organisms have been dependent on bacteria for a long time.

  Moreover, microbes provide humans with essential nutrients including carbon sources, nitrogen sources, phosphate sources, and iron sources . Plants have provided human with vast amount of nutrients; but in fact, microbes are found to generate much nutrient sources in comparison with plants (2): it is estimated that in our planet earth, microbes contain 85-130Pg of Nitrogen and 9-14 Pg of Phosphate, and those are about 10-fold more of these nutrient sources provided by plants. Thus, microbes represent the largest pool of these nutrient sources ever found in any living organisms (2) . Also, microbes provide human beings with huge amount of carbon sources. In fact, the total organic carbon content contained in sub-seafloor sediment is related to microbial biomass, since a clear relationship has been discovered between sub-seafloor microbial biomass and buried organic matter (3). Therefore, the inclusion of prokaryotic carbon in global models will almost double the estimated amount of carbon stored in living organisms, and the total amount of prokaryotic carbon has been estimated to be 60-100% of the total amount of carbon contained in plants (2). Furthermore, microbial life also contributes to the synthesis of iron. Archaean ironstone is found to be abundant, and iron has probably being transferred from this Archaeaon source to its place of deposition(2). The synthesis of iron has taken placed by Archaeaon processes. Overall, since the abundance of microbes  are related to the availability  of nutrient sources utilized by human beings, it is undeniable that microbial life provides human beings with essential nutrient sources such as Carbon, Nitrogen, Phosphate and Iron. Without prokaryotes, we can hardly acquire sufficient nutrients from plants or by engineering processes humans are utilizing.  
	
 Furthermore,  microbial processes have altered the composition of earth’s atmosphere and given rise to the environment that earth exists nowadays. In marine sediment, bacteria and archaea drive fundamental processes such as oxidation of organic matter, production of methane and other hydrocarbons, and removal of phosphate from ocean (3). Those processes have given risen to the composition of the ocean. Moreover, marine photosynthesis has provided planet earth with a net source of O2, the crucial component of earth’s atmosphere. Most marine photosynthesis is performed by single-celled organisms, and most abundant of these organisms are eukaryotic algae, such as diatoms and coccolithophorids (4). A small fraction (~0.1%) of the organic matter synthesized in the ocean is buried in sediments, and this small leak in the marine organic carbon cycle is responsible for most of our atmospheric O2 synthesis. Furthermore, cyanobacteria are universally believed to have been responsible for the initial rise of atmospheric O2 around 2.3 billion years ago. Today,  these bacteria, as well as microscopic algae, not only supply oxygen to the atmosphere, but also churn out fixed nitrogen in Earth’s vast oceans(4). Emergence of oxygen has driven a fundamental change in planet earth because oxygen is a crucial component of cellular respiration, giving rise to multi-cellular organisms, plants and animals; human beings cannot ever survive in an earth without O2. Finally, micro-organisms may have played a major role in atmosphere evolution even before the rise of oxygen. Certain groups of anaerobic bacteria known as methanogens may have been pumping out large amounts of methane, thereby keeping the early climate warm and inviting(4). Overall, microorganisms have determined the basic composition of Earth’s atmosphere even long before the existence of human beings. Microbial processes alter the earth’s atmosphere and determine ocean’s composition. Therefore, without the fundamental processes driven by microbial life, the planet earth would not be survivable for the species of human beings or other life forms. 

  Finally, unlike how human beings are dependent on the survival of microbial species, microbes can easily survive without any helps provided by human beings: microbes have existed long before the emergence of species of human beings, and microbes are found to survive in harsh environments such as in the ancient earth or high temperature or pH conditions; those environments aren’t tolerable for human beings. For instance, Archaea is an  evolutionarily ancient microbe, and has existed on primitive Earth and is responsible for the production of methane (3). Human beings aren’t able to live in an environment without atmospheric oxygen, whereas archaea is able to simply use methane as the energy source. Moreover, the first form of life that has ever existed in universe is speculated to be microbes. On earth, life probably dates from 3.8 Gyr or before, but life may have existed earlieron Mars or even Venus or an outer moon and been translated to Earth by meteorite (3). Such life form existed was likely to be in the form of microbe, and such life form is not dependent on the existence of any other types of life forms. Moreover, even in nowadays earth, microbes are found to live in harsh environments in parts of earth that aren’t livable for human beings. Extremophiles are discovered, and are found to thrive in habits which for humans, or even other terrestrial life forms are intolerably hostile or even lethal. Those organisms are found to live in various extreme habitats. They are found to live in depths of 6.7 km inside the Earth’s crust, more than 10 km deep inside the ocean-ay pressure of up to 110 MPa. Extremophiles are also found from extreme acid (pH 0) to extreme basic conditions (pH 12.8), and from hydrothermal vents at 122 °C to frozen sea water, at −20 °C (5). The survival of Extremophiles isn’t dependent on human beings such that this organism lives in conditions that aren’t tolerable to any life forms. Overall, since microbes are found various harsh conditions, we can conclude that the survival of microbes aren’t depend on human beings as how humans depend on microbes.  

  In conclusion, I support the statement such that  microbial life can easily live without us but we cannot survive without the global catalysis and environmental transformations that are provided by microbes. Microbes have existed in a mutualistic relationship with eukaryotes since eukaryotes cells first engulf prokaryotes which later becomes mitochondrion. Microbes provide human beings with vast amount of nutrients and resources; human beings will suffer from deficient of resources if simply rely upon nutrients supplied by plants. Also, microbial processes have given rise to earth’s atmosphere by contributing to the emergence of oxygen, generating an environment on planet earth that is survivable to human beings. Microbes have given risen the ancient earth as well. In addition, microbes have existed even since the discovered of the earliest life form, long before the existence of human beings. Even in earth nowadays, microbes are able to tolerate conditions that aren’t tolerable to human beings. Therefore, survival of microbial life is not dependent on human beings as how me must depend on microbes. 
  
**References**:

1. Gray, M. W., Burger, G., & Lang, B. F. (2001). The origin and early evolution of mitochondria. Genome biology, 2(6), reviews 1018-1. 

2. Whitman WB, Coleman DC, and Wiebe WJ. 1998. Prokaryotes: The unseen majority. Proc Natl Acad Sci USA. 95(12):6578–6583. 

3. Kallmeyer, J., Pockalny, R., Adhikari, R. R., Smith, D. C., & D’Hondt, S. (2012). Global distribution of microbial abundance and biomass in subseafloor sediment. Proceedings of the National Academy of Sciences, 109(40), 16213-16216. 

4. Kasting, J. F., & Siefert, J. L. (2002). Life and the evolution of Earth's atmosphere. Science, 296(5570), 1066-1068. 

5. Rampelotto, P. H. (2013). Extremophiles and extreme environments. 
