---
title: "Module 3 Essay"
author: "YiWei Yang (18422148)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

###Discuss the challenges involved in defining a microbial species and how HGT complicates matters, especially in the context of the evolution and phylogenetic distribution of microbial metabolic pathways.  Can you comment on how HGT influences the maintenance of global biogeochemical cycles through time?  Finally, do you think it is necessary to have a clear definition of a microbial species?  Why or why not?

   Definition of species made by human beings is very arbitrarily: microbes are grouped into same species even if they shared ~30% differences in genes. If such big differences are allowed to distinguish species between mammals, humans and chimpanzee could be defined as in the same species. Therefore, with such definition of species, microbes with very different biochemical, physiological and metabolic properties could be defined in the same species. Horizontal gene transfer further complicates this matters since the process allows for identical genes to be transferred between microbial species, thus the entire population of microbes become further interdependent and relatable. Also, horizontal gene transfer is a major process driving out the evolution of microbial species, since horizontal gene transfer allows for the acquisition and evolution of many traits including antibiotic resistance, pathogenesis, and bioremediation (2). Moreover, horizontal gene transfer influences on the maintenance of global biogeochemical cycles by microbial processes, since various enzymes-coding and nutrients-metabolizing genes are also transferred between microbes via HGT. Therefore, microbes have come to share similar metabolic enzymes, and microbes with different properties have come to colonize same ecosystems of earth using similar nutrient sources. However, even though that a lot of ambiguities exist in the definition of microbial species and with such matter further being complicated by horizontal gene transfer, I still believe that it is quite necessary to group microbes into species since the species-definition has a lot of utilities. 

  First of all, since horizontal gene transfer has allowed for the transfer of genetic materials between distinct species, definition of species has been complicated by the process of horizontal gene transfer. For instance, scientists have grouped organisms sharing very different genetic and physiological properties into species: pathogenic strain E.coli O157:H7 has unique properties than most strains of E.coli in which the species contain pathogenic islands, and over 20% of genes from E.coli O157:H7 are acquired by horizontal gene transfer. Regarding to E.coli O157:H7,  although its genome has not been completely sequenced, it is known to contain more than 20 potential virulence genes clustered in several mobile elements: the large plasmid pO157, the lambdoid temperate phage 933W, another cryptic prophage and the pathogenicity island LEE(1), and  majority of virulence genes in E.coli O157:H7 are acquired via horizontal gene transfer. Furthermore, horizontal gene transfer is also found to be a driving force behind the evolution of microbial species: in bacterial species, horizontal gene transfer is widely recognized as the mechanism responsible for the widespread distribution of antibiotic resistance genes, gene clusters encoding bio-degradative pathways and pathogenicity determinants (1).Therefore, organisms capable of performing horizontal gene transfer are more likely to obtain antibiotic resistance genes and other properties that enhanced their survival; they are more likely to possess evolutionary advantages. It is also important to point out that using E. coli and Salmonella as a model system, it has been shown that 17% of their genomes (i.e. ~800 kb), appears to have been acquired by horizontal gene transfer during the past 100 million years (the housekeeping genes of both organisms are ~90% identical) (1). Therefore, in this case horizontal gene transfer might be the driving process that distinguishes the two species (E.coli and Salmonella), since majority of their gene difference are acquired via horizontal gene transfer.  Also, since horizontal gene transfer has presented over historical time, this process is further implicated to be the driving force behind the evolution of those two organisms through acquisition of new genetic information. Overall, horizontal gene transfer has complicated the definition of species, since it is also known as the driving force that has given rise to the variety of species. Microbial world should be pointed out as interdependent. 

  Moreover, horizontal gene transfer not only has found to take place between prokaryotes to prokaryotes, but also between prokaryotes and eukaryotes; all types of species have be made to be further interdependent and relatable. Over past century, horizontal gene transfer has increasingly being observed between bacteria and animals existed in symbiotic relationship: one classic example is the transfer of DNA from mitochondria and chloroplasts to the nucleus after the acquisition of these organelles by eukaryotes (2). Because of horizontal gene transfer, many genes contained in the original mitochondria and chloroplast are found to contain in the eukaryotes. This process has allowed for mechanisms taken placed between prokaryotic and eukaryotic species becoming more efficient, since eukaryotes contain mitochondrial genes within the nucleus. Moreover, many of the described instances of bacteria to animal transfer occur as part between endosymbionts and their invertebrate hosts, particularly insects and nematodes, while numerous transfers are also found in asexual animals (2). For instance, the horizontal gene transfer to Drosophila ananassae from its Wolbachia endosymbiont resulting in the entire ~1.4 Mbp Wolbachia genome has been integrated into the D. ananassae Hawaii 2L chromosome. But the utility of such process is still not known to scientists. Finally, in some case horizontal gene transfer results in adaptation of microbial species: adaptation of the thermoacidophilic red alga Galdieria sulphuraria to its hot, acid, toxic-metal laden, volcanic environment was facilitated by the acquisition of numerous genes from extremophile bacteria and archaea (3). Such instances of adaptations are numerous, including ice-binding proteins in marine algae, enzymes for carotenoid biosynthesis in aphids, and genes involved in fungal metabolism, etc (3). Overall, we can conclude that numbers instances of horizontal gene transfer are also observed between prokaryotes and eukaryotes.  

 However, Syvanen, M. (1994) has pointed out that that horizontal gene transfer not necessarily preclude from making phylogenetic classification of species, but indeed have made it more difficult (4).  He has given an example of angiosperms: these taxonomic groups can be organized into tree-like patterns of descent occurred in the presence of horizontal gene transfer. Horizontal gene transfer indeed contributed to the transfer of crucial genetic information between these species, but does not prevent scientists from inferring the evolutionary relationship between species of angiosperms; genes transferred between species via horizontal gene transfer has considered as a source of genetic variation, but cross-species gene transfer could logically exist concomitantly with reproductive isolation and other biological barriers (4). Therefore, regarding to the example of angiosperm, horizontal gene transfer not necessary prevent scientists from making phylogenetic classification and inferring the evolutionarily relationship. However, it is certain that horizontal gene transfer has made phylogenetic classification of species more difficult.  
   
  Furthermore, horizontal gene transfer also contributes to the maintenance of biogeochemical cycle on the planet earth. Abundance of microbes is correlated with turnover rates of major reservoirs in the planet earth, so that microbial processes have impacted the global biogeochemical cycles. As noted previously that microbes capable of performing horizontal gene transfer have evolutionary advantages since they acquired ability to utilize greater variety of genes. Thus microbes capable of performing HGT acquired nutrient-metabolizing genes to enhance their survival. The importance of the microbial community composition, their metabolic state, and the activity of enzymes for the fate and degradation of specific substrates such as chitin, the degradation of more complex compounds such as those constituting plant litter, and the metabolism and biogeochemical cycling of one-carbon compounds, have a great impact on the turnover rates of nutrients (5).  So that turnover rates of nutrients are dependent on processes that microbes are capable of performing, and whether microbes can perform those processes are dependent on whether they have specific enzymes-encoding genes. Such genes can be widely distributed around the microbial world via horizontal gene transfer. Moreover, plant-microbial feedbacks for the regulation of organic matter decomposition and formation has been noted to be an important process in regulating abundance of nutrients (5). As mentioned previously, horizontal gene transfer has been observed between eukaryotes-prokaryotes in symbiotic relationship, and this process might contribute to the co-evolution of both eukaryotes and prokaryotes and enhance cooperative relationship between eukaryotes and prokaryotes. Finally, Rousk, J., & Bengtson, P. (2014) also notes the importance of interactions between different biogeochemical cycles for nitrogen fixation in ecosystems with nitrogen-limited plant productivity. Various nitrogen-fixing, nitrifying and denitrifying enzymes have also became widely distributed among microbial species via the process of horizontal gene transfer. Wide variety of microbes become capable of performing those processes. Overall, horizontal gene transfer inevitably has contributed to the maintenance of biogeochemical cycle over time.  

  Finally, definition of species made by human beings is arbitrarily, and with horizontal gene transfer, it is undeniable that defining species has become ambiguous and burred. But I still believe that it is necessary to have a clear definition of species, since microbes within a species still shared around 70% of similar genes, thus many physiological, biochemical and metabolic properties. Definition of species will allow scientists, researchers and medicine practioners to communicate research’s findings easily, since it allows for identification of types of species being referred to by professionals; they are able to form basic understanding regarding various properties of species that are being described, since microbes within species still share great numbers physiological and biochemical properties. Moreover, by first grouping microorganisms into species, scientists can infer the evolutionary relationship between microorganism: organisms within a species are expected to have more recent common ancestors. We can also infer the emergence sequence of species on the planet earth by understanding of the evolutionary relationship between microorganisms. And by having a clearer idea of the evolutionary relationship between microbial species, we can have a better understanding of the evolutionary history of the planet earth over centuries. Therefore, because of those reasons, I still believe that it is quite important to group microorganisms into species.

  In conclusion, horizontal gene transfer has been a common mechanism of gene transfer across nature. Horizontal gene transfer has not only been found to occur between prokaryotes, but also between prokaryotes and eukaryotes. Because of horizontal gene transfer, organisms are able to obtain genetic information from other species, pass on genetic information to other species, and even to species that are found to be evolutionarily distanced. Horizontal gene transfer also drives the evolutionary process: organisms capable of performing horizontal gene transfer can acquire genes that enhanced survival, thus such organisms indeed possess evolutionary advantages. Furthermore, since horizontal gene transfer allows microbes to acquire similar genetic information and able to perform similar metabolic processes, it is crucial for the maintenance of biogeochemical cycle on earth over historical time by microorganisms. 

**References**:

1.	De la Cruz, F., & Davies, J. (2000). Horizontal gene transfer and the origin of species: lessons from bacteria. Trends in microbiology, 8(3), 128-133.

2.	Hotopp, J. C. D. (2011). Horizontal gene transfer between bacteria and animals. Trends in Genetics, 27(4), 157-163.

3.	Schönknecht, G., Weber, A. P., & Lercher, M. J. (2014). Horizontal gene acquisitions by eukaryotes as drivers of adaptive evolution. Bioessays, 36(1), 9-20.

4.	Syvanen, M. (1994). Horizontal gene transfer: evidence and possible consequences. Annual review of genetics, 28(1), 237-261.

5.	Rousk, J., & Bengtson, P. (2014). Microbial regulation of global biogeochemical cycles. Frontiers in microbiology, 5, 103.



